apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ashuclaim
  namespace: ashutoshh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast
