apiVersion: v1
kind: Pod
metadata:
  name: mypodashu
  namespace: ashutoshh
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: myspace
  volumes:
    - name: myspace
      persistentVolumeClaim:
        claimName: ashuclaim 
