apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podashu1
  name: podashu1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - ping google.com
    image: 35.167.232.210:5000/ashuimg:v1
    name: c1
  - command:
    - /bin/sh
    - -c
    - ping google.com
    image: alpine
    name: c2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
