apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashumypod
  name: ashumypod
spec:
  containers:
  - image: nginx
    name: ashumypod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
