apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    key1: value1000
  name: pod2svc
spec:
  ports:
  - name: "1234"
    port: 80
    protocol: TCP
    targetPort: 1234
  selector:
    key1: value1000
  type: NodePort
status:
  loadBalancer: {}
