apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    key1: value1000
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
